name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args:  --all -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args:  -- -A clippy::too-many-arguments -D warnings

    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Run tests
      run: cargo test --verbose
